### ISSUE TITLE
Settings files are difficult for users to locate after saving

### ISSUE THREAD

**Issue by TarogStar** [YesWeCandrew/XTBPlugins.DataImport#14]
The Open dialog should go to the Xrm Toolbox settings folder when opened instead of to the default location which makes it really hard for end users to find if you don't allow the save dialog to choose a normal location.  To fix this either allow the user to save to a folder of their choosing, or make the Open dialog default to the Xrm Toolbox settings folder.  I would prefer for the save to go to a user chosen location, because there are a lot of xml settings files in that default folder that could confuse an end user.

**Comment by YesWeCandrew** [comment]
Hey @TarogStar this has been corrected with the latest release
